# Site
repository: freestatman/freestatman.github.io
favicon: images/favicon.ico

# Personal info
name: Freeman Wang
title: Data Science Director
email: freestatman@gmail.com
website: http://freestatman.github.io

# Social links
twitter_username: freestatman
github_username:  freestatman
linkedin_username: shuaicheng-freeman-wang-4157ba23

# About Section
# about_title: About Me
about_profile_image: images/twitter_profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Freeman has eight years of statistical consulting experience in the
  pharmaceutical and biotechnology industries. Technically, he is a full-stack expert-level
  <mark>R/Shiny developer</mark>,
  <mark>biostatistician</mark>,
  <mark>machine learning data scientist</mark>,
  <mark>visualization engineer</mark>, and
  <mark>bioinformatician/computational biologist</mark>.
  Organizationally, Freeman supervises and mentors a team of data scientist,
  statistician and statistical specialist. Freeman has deep experience in statistical inference, modeling and complex data, and extensive hands-on research experience on transcriptomic data analysis (RNA-seq, single cell), drug target identification, Genome-Wide Association Studies (GWAS), in the area of precision medicine and biomarker discovery. Freeman is enthusiastic on emerging technology in R/Pharma and life science communities, and onboarding new best practice and reproducible workflows into organization and projects, e.g. web app design & development, reproducible research, DevOps, databases, data harmonization from a variety of genotypic platforms and pharmacogenomics (PGx) studies.  
  Over the years, Freeman helped the team build and strengthen long-term client relationships through quality work and innovation, collaboration & communication, as well as a strong customer service mindset. Therapeutic areas include Diabetes, CNS, Gastroenterology, Oncology, and Immunology.

  Skills Highlight: 
  <mark>R/Shiny</mark>, 
  <mark>Tidyverse</mark>, 
  <mark>Statistics</mark>, 
  <mark>Visualization</mark>, 
  <mark>Azure/AWS</mark>, 
  <mark>Linux</mark>, 
  <mark>CI/CD</mark>, <mark>UI/UX</mark>, 
  and <mark>ML(TidyModels)</mark>.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in #rstats, some of my other interests are:
   - Running and hiking with my dog
   - Spending time with my wife, kid, friends, and text editors (Vim and VScode)


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
